extend type Mutation {
  """
  ✨ Insert a single `Grade` into the table and return its key. Columns not specified in `data` will receive defaults (e.g. `null`).
  """
  grade_insert(
    """
    Data object to insert into the table.
    """
    data: Grade_Data!
  ): Grade_KeyOutput! @fdc_generated(from: "Grade", purpose: INSERT_SINGLE)
  """
  ✨ Insert a single `Term` into the table and return its key. Columns not specified in `data` will receive defaults (e.g. `null`).
  """
  term_insert(
    """
    Data object to insert into the table.
    """
    data: Term_Data!
  ): Term_KeyOutput! @fdc_generated(from: "Term", purpose: INSERT_SINGLE)
  """
  ✨ Insert `Grade` objects into the table and return their keys. Columns not specified in `data` will receive defaults (e.g. `null`).
  """
  grade_insertMany(
    """
    List of data objects to insert into the table.
    """
    data: [Grade_Data!]!
  ): [Grade_KeyOutput!]! @fdc_generated(from: "Grade", purpose: INSERT_MULTIPLE)
  """
  ✨ Insert `Term` objects into the table and return their keys. Columns not specified in `data` will receive defaults (e.g. `null`).
  """
  term_insertMany(
    """
    List of data objects to insert into the table.
    """
    data: [Term_Data!]!
  ): [Term_KeyOutput!]! @fdc_generated(from: "Term", purpose: INSERT_MULTIPLE)
  """
  ✨ Insert or update a single `Grade` into the table, based on the primary key. Returns the key of the newly inserted or existing updated `Grade`.
  """
  grade_upsert(
    """
    Data object to insert or update if it already exists.
    """
    data: Grade_Data!
  ): Grade_KeyOutput! @fdc_generated(from: "Grade", purpose: UPSERT_SINGLE)
  """
  ✨ Insert or update a single `Term` into the table, based on the primary key. Returns the key of the newly inserted or existing updated `Term`.
  """
  term_upsert(
    """
    Data object to insert or update if it already exists.
    """
    data: Term_Data!
  ): Term_KeyOutput! @fdc_generated(from: "Term", purpose: UPSERT_SINGLE)
  """
  ✨ Insert or update `Grade` objects into the table, based on the primary key. Returns the key of the newly inserted or existing updated `Grade`.
  """
  grade_upsertMany(
    """
    List of data objects to insert or update if it already exists.
    """
    data: [Grade_Data!]!
  ): [Grade_KeyOutput!]! @fdc_generated(from: "Grade", purpose: UPSERT_MULTIPLE)
  """
  ✨ Insert or update `Term` objects into the table, based on the primary key. Returns the key of the newly inserted or existing updated `Term`.
  """
  term_upsertMany(
    """
    List of data objects to insert or update if it already exists.
    """
    data: [Term_Data!]!
  ): [Term_KeyOutput!]! @fdc_generated(from: "Term", purpose: UPSERT_MULTIPLE)
  """
  ✨ Update a single `Grade` based on `id`, `key` or `first`, setting columns specified in `data`. Returns the key of the updated `Grade` or `null` if not found.
  """
  grade_update(
    """
    The unique ID of the object.
    """
    id: UUID

    """
    The key used to identify the object.
    """
    key: Grade_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: Grade_FirstRow

    """
    Data object containing fields to be updated.
    """
    data: Grade_Data!
  ): Grade_KeyOutput @fdc_generated(from: "Grade", purpose: UPDATE_SINGLE)
  """
  ✨ Update a single `Term` based on `id`, `key` or `first`, setting columns specified in `data`. Returns the key of the updated `Term` or `null` if not found.
  """
  term_update(
    """
    The unique ID of the object.
    """
    id: String

    """
    ✨ `_expr` server value variant of `id` (The unique ID of the object.)
    """
    id_expr: String_Expr

    """
    The key used to identify the object.
    """
    key: Term_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: Term_FirstRow

    """
    Data object containing fields to be updated.
    """
    data: Term_Data!
  ): Term_KeyOutput @fdc_generated(from: "Term", purpose: UPDATE_SINGLE)
  """
  ✨ Update `Grade` objects matching `where` conditions (or `all`, if true) according to `data`. Returns the number of rows updated.
  """
  grade_updateMany(
    """
    Filter condition to specify which rows to update.
    """
    where: Grade_Filter

    """
    Set to true to update all rows.
    """
    all: Boolean = false

    """
    Data object containing fields to update.
    """
    data: Grade_Data!
  ): Int! @fdc_generated(from: "Grade", purpose: UPDATE_MULTIPLE)
  """
  ✨ Update `Term` objects matching `where` conditions (or `all`, if true) according to `data`. Returns the number of rows updated.
  """
  term_updateMany(
    """
    Filter condition to specify which rows to update.
    """
    where: Term_Filter

    """
    Set to true to update all rows.
    """
    all: Boolean = false

    """
    Data object containing fields to update.
    """
    data: Term_Data!
  ): Int! @fdc_generated(from: "Term", purpose: UPDATE_MULTIPLE)
  """
  ✨ Delete a single `Grade` based on `id`, `key` or `first` and return its key (or `null` if not found).
  """
  grade_delete(
    """
    The unique ID of the object.
    """
    id: UUID

    """
    The key used to identify the object.
    """
    key: Grade_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: Grade_FirstRow
  ): Grade_KeyOutput @fdc_generated(from: "Grade", purpose: DELETE_SINGLE)
  """
  ✨ Delete a single `Term` based on `id`, `key` or `first` and return its key (or `null` if not found).
  """
  term_delete(
    """
    The unique ID of the object.
    """
    id: String

    """
    ✨ `_expr` server value variant of `id` (The unique ID of the object.)
    """
    id_expr: String_Expr

    """
    The key used to identify the object.
    """
    key: Term_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: Term_FirstRow
  ): Term_KeyOutput @fdc_generated(from: "Term", purpose: DELETE_SINGLE)
  """
  ✨ Delete `Grade` objects matching `where` conditions (or `all`, if true). Returns the number of rows deleted.
  """
  grade_deleteMany(
    """
    Filter condition to specify which rows to delete.
    """
    where: Grade_Filter

    """
    Set to true to delete all rows.
    """
    all: Boolean = false
  ): Int! @fdc_generated(from: "Grade", purpose: DELETE_MULTIPLE)
  """
  ✨ Delete `Term` objects matching `where` conditions (or `all`, if true). Returns the number of rows deleted.
  """
  term_deleteMany(
    """
    Filter condition to specify which rows to delete.
    """
    where: Term_Filter

    """
    Set to true to delete all rows.
    """
    all: Boolean = false
  ): Int! @fdc_generated(from: "Term", purpose: DELETE_MULTIPLE)
}
