extend type Mutation {
  """
  ✨ Insert a single `Author` into the table and return its key. Columns not specified in `data` will receive defaults (e.g. `null`).
  """
  author_insert(
    """
    Data object to insert into the table.
    """
    data: Author_Data!
  ): Author_KeyOutput! @fdc_generated(from: "Author", purpose: INSERT_SINGLE)
  """
  ✨ Insert a single `Book` into the table and return its key. Columns not specified in `data` will receive defaults (e.g. `null`).
  """
  book_insert(
    """
    Data object to insert into the table.
    """
    data: Book_Data!
  ): Book_KeyOutput! @fdc_generated(from: "Book", purpose: INSERT_SINGLE)
  """
  ✨ Insert a single `Borrowing` into the table and return its key. Columns not specified in `data` will receive defaults (e.g. `null`).
  """
  borrowing_insert(
    """
    Data object to insert into the table.
    """
    data: Borrowing_Data!
  ): Borrowing_KeyOutput! @fdc_generated(from: "Borrowing", purpose: INSERT_SINGLE)
  """
  ✨ Insert a single `Member` into the table and return its key. Columns not specified in `data` will receive defaults (e.g. `null`).
  """
  member_insert(
    """
    Data object to insert into the table.
    """
    data: Member_Data!
  ): Member_KeyOutput! @fdc_generated(from: "Member", purpose: INSERT_SINGLE)
  """
  ✨ Insert `Author` objects into the table and return their keys. Columns not specified in `data` will receive defaults (e.g. `null`).
  """
  author_insertMany(
    """
    List of data objects to insert into the table.
    """
    data: [Author_Data!]!
  ): [Author_KeyOutput!]! @fdc_generated(from: "Author", purpose: INSERT_MULTIPLE)
  """
  ✨ Insert `Book` objects into the table and return their keys. Columns not specified in `data` will receive defaults (e.g. `null`).
  """
  book_insertMany(
    """
    List of data objects to insert into the table.
    """
    data: [Book_Data!]!
  ): [Book_KeyOutput!]! @fdc_generated(from: "Book", purpose: INSERT_MULTIPLE)
  """
  ✨ Insert `Borrowing` objects into the table and return their keys. Columns not specified in `data` will receive defaults (e.g. `null`).
  """
  borrowing_insertMany(
    """
    List of data objects to insert into the table.
    """
    data: [Borrowing_Data!]!
  ): [Borrowing_KeyOutput!]! @fdc_generated(from: "Borrowing", purpose: INSERT_MULTIPLE)
  """
  ✨ Insert `Member` objects into the table and return their keys. Columns not specified in `data` will receive defaults (e.g. `null`).
  """
  member_insertMany(
    """
    List of data objects to insert into the table.
    """
    data: [Member_Data!]!
  ): [Member_KeyOutput!]! @fdc_generated(from: "Member", purpose: INSERT_MULTIPLE)
  """
  ✨ Insert or update a single `Author` into the table, based on the primary key. Returns the key of the newly inserted or existing updated `Author`.
  """
  author_upsert(
    """
    Data object to insert or update if it already exists.
    """
    data: Author_Data!
  ): Author_KeyOutput! @fdc_generated(from: "Author", purpose: UPSERT_SINGLE)
  """
  ✨ Insert or update a single `Book` into the table, based on the primary key. Returns the key of the newly inserted or existing updated `Book`.
  """
  book_upsert(
    """
    Data object to insert or update if it already exists.
    """
    data: Book_Data!
  ): Book_KeyOutput! @fdc_generated(from: "Book", purpose: UPSERT_SINGLE)
  """
  ✨ Insert or update a single `Borrowing` into the table, based on the primary key. Returns the key of the newly inserted or existing updated `Borrowing`.
  """
  borrowing_upsert(
    """
    Data object to insert or update if it already exists.
    """
    data: Borrowing_Data!
  ): Borrowing_KeyOutput! @fdc_generated(from: "Borrowing", purpose: UPSERT_SINGLE)
  """
  ✨ Insert or update a single `Member` into the table, based on the primary key. Returns the key of the newly inserted or existing updated `Member`.
  """
  member_upsert(
    """
    Data object to insert or update if it already exists.
    """
    data: Member_Data!
  ): Member_KeyOutput! @fdc_generated(from: "Member", purpose: UPSERT_SINGLE)
  """
  ✨ Insert or update `Author` objects into the table, based on the primary key. Returns the key of the newly inserted or existing updated `Author`.
  """
  author_upsertMany(
    """
    List of data objects to insert or update if it already exists.
    """
    data: [Author_Data!]!
  ): [Author_KeyOutput!]! @fdc_generated(from: "Author", purpose: UPSERT_MULTIPLE)
  """
  ✨ Insert or update `Book` objects into the table, based on the primary key. Returns the key of the newly inserted or existing updated `Book`.
  """
  book_upsertMany(
    """
    List of data objects to insert or update if it already exists.
    """
    data: [Book_Data!]!
  ): [Book_KeyOutput!]! @fdc_generated(from: "Book", purpose: UPSERT_MULTIPLE)
  """
  ✨ Insert or update `Borrowing` objects into the table, based on the primary key. Returns the key of the newly inserted or existing updated `Borrowing`.
  """
  borrowing_upsertMany(
    """
    List of data objects to insert or update if it already exists.
    """
    data: [Borrowing_Data!]!
  ): [Borrowing_KeyOutput!]! @fdc_generated(from: "Borrowing", purpose: UPSERT_MULTIPLE)
  """
  ✨ Insert or update `Member` objects into the table, based on the primary key. Returns the key of the newly inserted or existing updated `Member`.
  """
  member_upsertMany(
    """
    List of data objects to insert or update if it already exists.
    """
    data: [Member_Data!]!
  ): [Member_KeyOutput!]! @fdc_generated(from: "Member", purpose: UPSERT_MULTIPLE)
  """
  ✨ Update a single `Author` based on `id`, `key` or `first`, setting columns specified in `data`. Returns the key of the updated `Author` or `null` if not found.
  """
  author_update(
    """
    The unique ID of the object.
    """
    id: UUID

    """
    The key used to identify the object.
    """
    key: Author_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: Author_FirstRow

    """
    Data object containing fields to be updated.
    """
    data: Author_Data!
  ): Author_KeyOutput @fdc_generated(from: "Author", purpose: UPDATE_SINGLE)
  """
  ✨ Update a single `Book` based on `id`, `key` or `first`, setting columns specified in `data`. Returns the key of the updated `Book` or `null` if not found.
  """
  book_update(
    """
    The unique ID of the object.
    """
    id: UUID

    """
    The key used to identify the object.
    """
    key: Book_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: Book_FirstRow

    """
    Data object containing fields to be updated.
    """
    data: Book_Data!
  ): Book_KeyOutput @fdc_generated(from: "Book", purpose: UPDATE_SINGLE)
  """
  ✨ Update a single `Borrowing` based on `id`, `key` or `first`, setting columns specified in `data`. Returns the key of the updated `Borrowing` or `null` if not found.
  """
  borrowing_update(
    """
    The unique ID of the object.
    """
    id: UUID

    """
    The key used to identify the object.
    """
    key: Borrowing_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: Borrowing_FirstRow

    """
    Data object containing fields to be updated.
    """
    data: Borrowing_Data!
  ): Borrowing_KeyOutput @fdc_generated(from: "Borrowing", purpose: UPDATE_SINGLE)
  """
  ✨ Update a single `Member` based on `id`, `key` or `first`, setting columns specified in `data`. Returns the key of the updated `Member` or `null` if not found.
  """
  member_update(
    """
    The unique ID of the object.
    """
    id: UUID

    """
    The key used to identify the object.
    """
    key: Member_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: Member_FirstRow

    """
    Data object containing fields to be updated.
    """
    data: Member_Data!
  ): Member_KeyOutput @fdc_generated(from: "Member", purpose: UPDATE_SINGLE)
  """
  ✨ Update `Author` objects matching `where` conditions (or `all`, if true) according to `data`. Returns the number of rows updated.
  """
  author_updateMany(
    """
    Filter condition to specify which rows to update.
    """
    where: Author_Filter

    """
    Set to true to update all rows.
    """
    all: Boolean = false

    """
    Data object containing fields to update.
    """
    data: Author_Data!
  ): Int! @fdc_generated(from: "Author", purpose: UPDATE_MULTIPLE)
  """
  ✨ Update `Book` objects matching `where` conditions (or `all`, if true) according to `data`. Returns the number of rows updated.
  """
  book_updateMany(
    """
    Filter condition to specify which rows to update.
    """
    where: Book_Filter

    """
    Set to true to update all rows.
    """
    all: Boolean = false

    """
    Data object containing fields to update.
    """
    data: Book_Data!
  ): Int! @fdc_generated(from: "Book", purpose: UPDATE_MULTIPLE)
  """
  ✨ Update `Borrowing` objects matching `where` conditions (or `all`, if true) according to `data`. Returns the number of rows updated.
  """
  borrowing_updateMany(
    """
    Filter condition to specify which rows to update.
    """
    where: Borrowing_Filter

    """
    Set to true to update all rows.
    """
    all: Boolean = false

    """
    Data object containing fields to update.
    """
    data: Borrowing_Data!
  ): Int! @fdc_generated(from: "Borrowing", purpose: UPDATE_MULTIPLE)
  """
  ✨ Update `Member` objects matching `where` conditions (or `all`, if true) according to `data`. Returns the number of rows updated.
  """
  member_updateMany(
    """
    Filter condition to specify which rows to update.
    """
    where: Member_Filter

    """
    Set to true to update all rows.
    """
    all: Boolean = false

    """
    Data object containing fields to update.
    """
    data: Member_Data!
  ): Int! @fdc_generated(from: "Member", purpose: UPDATE_MULTIPLE)
  """
  ✨ Delete a single `Author` based on `id`, `key` or `first` and return its key (or `null` if not found).
  """
  author_delete(
    """
    The unique ID of the object.
    """
    id: UUID

    """
    The key used to identify the object.
    """
    key: Author_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: Author_FirstRow
  ): Author_KeyOutput @fdc_generated(from: "Author", purpose: DELETE_SINGLE)
  """
  ✨ Delete a single `Book` based on `id`, `key` or `first` and return its key (or `null` if not found).
  """
  book_delete(
    """
    The unique ID of the object.
    """
    id: UUID

    """
    The key used to identify the object.
    """
    key: Book_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: Book_FirstRow
  ): Book_KeyOutput @fdc_generated(from: "Book", purpose: DELETE_SINGLE)
  """
  ✨ Delete a single `Borrowing` based on `id`, `key` or `first` and return its key (or `null` if not found).
  """
  borrowing_delete(
    """
    The unique ID of the object.
    """
    id: UUID

    """
    The key used to identify the object.
    """
    key: Borrowing_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: Borrowing_FirstRow
  ): Borrowing_KeyOutput @fdc_generated(from: "Borrowing", purpose: DELETE_SINGLE)
  """
  ✨ Delete a single `Member` based on `id`, `key` or `first` and return its key (or `null` if not found).
  """
  member_delete(
    """
    The unique ID of the object.
    """
    id: UUID

    """
    The key used to identify the object.
    """
    key: Member_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: Member_FirstRow
  ): Member_KeyOutput @fdc_generated(from: "Member", purpose: DELETE_SINGLE)
  """
  ✨ Delete `Author` objects matching `where` conditions (or `all`, if true). Returns the number of rows deleted.
  """
  author_deleteMany(
    """
    Filter condition to specify which rows to delete.
    """
    where: Author_Filter

    """
    Set to true to delete all rows.
    """
    all: Boolean = false
  ): Int! @fdc_generated(from: "Author", purpose: DELETE_MULTIPLE)
  """
  ✨ Delete `Book` objects matching `where` conditions (or `all`, if true). Returns the number of rows deleted.
  """
  book_deleteMany(
    """
    Filter condition to specify which rows to delete.
    """
    where: Book_Filter

    """
    Set to true to delete all rows.
    """
    all: Boolean = false
  ): Int! @fdc_generated(from: "Book", purpose: DELETE_MULTIPLE)
  """
  ✨ Delete `Borrowing` objects matching `where` conditions (or `all`, if true). Returns the number of rows deleted.
  """
  borrowing_deleteMany(
    """
    Filter condition to specify which rows to delete.
    """
    where: Borrowing_Filter

    """
    Set to true to delete all rows.
    """
    all: Boolean = false
  ): Int! @fdc_generated(from: "Borrowing", purpose: DELETE_MULTIPLE)
  """
  ✨ Delete `Member` objects matching `where` conditions (or `all`, if true). Returns the number of rows deleted.
  """
  member_deleteMany(
    """
    Filter condition to specify which rows to delete.
    """
    where: Member_Filter

    """
    Set to true to delete all rows.
    """
    all: Boolean = false
  ): Int! @fdc_generated(from: "Member", purpose: DELETE_MULTIPLE)
}
