extend type Query {
  """
  ✨ Look up a single `Grade` based on `id`, `key` or `first` and return selected fields (or `null` if not found).
  """
  grade(
    """
    The unique ID of the object.
    """
    id: UUID

    """
    The key used to identify the object.
    """
    key: Grade_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: Grade_FirstRow
  ): Grade @fdc_generated(from: "Grade", purpose: QUERY_SINGLE)
  """
  ✨ Look up a single `Term` based on `id`, `key` or `first` and return selected fields (or `null` if not found).
  """
  term(
    """
    The unique ID of the object.
    """
    id: String

    """
    ✨ `_expr` server value variant of `id` (The unique ID of the object.)
    """
    id_expr: String_Expr

    """
    The key used to identify the object.
    """
    key: Term_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: Term_FirstRow
  ): Term @fdc_generated(from: "Term", purpose: QUERY_SINGLE)
  """
  ✨ List `Grade` objects in the table and return selected fields, optionally filtered by `where` conditions
  """
  grades(
    """
    Filter condition to narrow down the query results.
    """
    where: Grade_Filter

    """
    Order the query results by specific fields.
    """
    orderBy: [Grade_Order!]

    """
    Number of rows to skip before starting to return the results.
    """
    offset: Int

    """
    Maximum number of rows to return (defaults to 100 rows).
    """
    limit: Int = 100

    """
    Set to true to return distinct results.
    """
    distinct: Boolean = false

    """
    Filter condition to apply to the groups of aggregate queries.
    """
    having: Grade_Having
  ): [Grade!]! @fdc_generated(from: "Grade", purpose: QUERY_MULTIPLE)
  """
  ✨ List `Term` objects in the table and return selected fields, optionally filtered by `where` conditions
  """
  terms(
    """
    Filter condition to narrow down the query results.
    """
    where: Term_Filter

    """
    Order the query results by specific fields.
    """
    orderBy: [Term_Order!]

    """
    Number of rows to skip before starting to return the results.
    """
    offset: Int

    """
    Maximum number of rows to return (defaults to 100 rows).
    """
    limit: Int = 100

    """
    Set to true to return distinct results.
    """
    distinct: Boolean = false

    """
    Filter condition to apply to the groups of aggregate queries.
    """
    having: Term_Having
  ): [Term!]! @fdc_generated(from: "Term", purpose: QUERY_MULTIPLE)
}
