extend type Grade {
  """
  Implicit metadata field that cannot be written. It provides extra information about query results.
  """
  _metadata: _Metadata @fdc_generated(from: "Grade", purpose: METADATA_FIELD)
  """
  ✨ Count the number of rows in the `Grade` table.
  """
  _count: Int! @fdc_generated(from: "Grade.", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `Grade` table where the `gradeValue` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  gradeValue_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "Grade.gradeValue", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `Grade` table where the `id` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  id_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "Grade.id", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `Grade` table where the `instructorName` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  instructorName_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "Grade.instructorName", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `Grade` table where the `publishedAt` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  publishedAt_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "Grade.publishedAt", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `Grade` table where the `publishedBy` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  publishedBy_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "Grade.publishedBy", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `Grade` table where the `remarks` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  remarks_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "Grade.remarks", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `Grade` table where the `status` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  status_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "Grade.status", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `Grade` table where the `studentId` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  studentId_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "Grade.studentId", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `Grade` table where the `subjectCode` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  subjectCode_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "Grade.subjectCode", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `Grade` table where the `subjectTitle` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  subjectTitle_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "Grade.subjectTitle", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `Grade` table where the `termId` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  termId_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "Grade.termId", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `Grade` table where the `units` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  units_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "Grade.units", purpose: QUERY_COUNT)
  """
  ✨ Sum the `units` field in the `Grade` table.
  """
  units_sum(
    """
    Set to true to sum the distinct values.
    """
    distinct: Boolean = false
  ): Int @fdc_generated(from: "Grade.units", purpose: QUERY_SUM)
  """
  ✨ Average the `units` field in the `Grade` table.
  """
  units_avg(
    """
    Set to true to average the distinct values.
    """
    distinct: Boolean = false
  ): Float @fdc_generated(from: "Grade.units", purpose: QUERY_AVG)
  """
  ✨ Minimum of the `publishedAt` field in the `Grade` table.
  """
  publishedAt_min: Timestamp @fdc_generated(from: "Grade.publishedAt", purpose: QUERY_MIN)
  """
  ✨ Minimum of the `units` field in the `Grade` table.
  """
  units_min: Int @fdc_generated(from: "Grade.units", purpose: QUERY_MIN)
  """
  ✨ Maximum of the `publishedAt` field in the `Grade` table.
  """
  publishedAt_max: Timestamp @fdc_generated(from: "Grade.publishedAt", purpose: QUERY_MAX)
  """
  ✨ Maximum of the `units` field in the `Grade` table.
  """
  units_max: Int @fdc_generated(from: "Grade.units", purpose: QUERY_MAX)
  """
  A generated field that is used for caching results in SDKs.
  """
  _id: ID! @fdc_generated(from: "Grade.id", purpose: GLOBAL_ID)
}
extend type Term {
  """
  Implicit metadata field that cannot be written. It provides extra information about query results.
  """
  _metadata: _Metadata @fdc_generated(from: "Term", purpose: METADATA_FIELD)
  """
  ✨ Count the number of rows in the `Term` table.
  """
  _count: Int! @fdc_generated(from: "Term.", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `Term` table where the `endDate` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  endDate_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "Term.endDate", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `Term` table where the `id` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  id_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "Term.id", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `Term` table where the `name` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  name_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "Term.name", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `Term` table where the `startDate` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  startDate_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "Term.startDate", purpose: QUERY_COUNT)
  """
  ✨ Minimum of the `endDate` field in the `Term` table.
  """
  endDate_min: Timestamp @fdc_generated(from: "Term.endDate", purpose: QUERY_MIN)
  """
  ✨ Minimum of the `startDate` field in the `Term` table.
  """
  startDate_min: Timestamp @fdc_generated(from: "Term.startDate", purpose: QUERY_MIN)
  """
  ✨ Maximum of the `endDate` field in the `Term` table.
  """
  endDate_max: Timestamp @fdc_generated(from: "Term.endDate", purpose: QUERY_MAX)
  """
  ✨ Maximum of the `startDate` field in the `Term` table.
  """
  startDate_max: Timestamp @fdc_generated(from: "Term.startDate", purpose: QUERY_MAX)
  """
  A generated field that is used for caching results in SDKs.
  """
  _id: ID! @fdc_generated(from: "Term.id", purpose: GLOBAL_ID)
}
